import { useState } from 'react';
import { Platform, View } from 'react-native';
import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import { useAuth } from '../../src/auth/context';
import { API_URL, messageOf } from '../../src/api/client';
import { space, useColors } from '../../src/theme/tokens';
import { Screen, Header } from '../../src/ui/Screen';
import { HeroBanner } from '../../src/ui/HeroBanner';
import { T } from '../../src/ui/Text';
import { Button } from '../../src/ui/Button';
import { Icon, type IconName } from '../../src/ui/Icon';
import { Banner } from '../../src/ui/Feedback';
import { localToday } from '../../src/lib/dates';

/**
 * EXPORT (FR-A6, store-readiness.md: never behind a paywall). CSV for a
 * spreadsheet, JSON for everything. Generated by the worker, handed to the
 * system share sheet.
 */

const WHAT: { icon: IconName; text: string }[] = [
  { icon: 'inbox', text: 'Every deadline — open and done — with dates, amounts and notes' },
  { icon: 'bell', text: 'Each item’s reminder settings' },
  { icon: 'users', text: 'Your household and who handles what' },
];

export default function Export() {
  const c = useColors();
  const { session } = useAuth();
  const [busy, setBusy] = useState<'csv' | 'json' | null>(null);
  const [done, setDone] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const run = async (format: 'csv' | 'json') => {
    setBusy(format);
    setError(null);
    setDone(null);
    try {
      const url = `${API_URL}/api/v1/export?format=${format}`;
      const name = `duebox-${localToday()}.${format}`;
      if (Platform.OS === 'web') {
        const res = await fetch(url, { headers: { authorization: `Bearer ${session?.accessToken ?? ''}` } });
        if (!res.ok) throw new Error('The export didn’t download. Try again.');
        const blob = await res.blob();
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = name;
        link.click();
      } else {
        const target = `${FileSystem.cacheDirectory}${name}`;
        const res = await FileSystem.downloadAsync(url, target, { headers: { authorization: `Bearer ${session?.accessToken ?? ''}` } });
        if (res.status !== 200) throw new Error('The export didn’t download. Try again.');
        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(res.uri, {
            mimeType: format === 'csv' ? 'text/csv' : 'application/json',
            UTI: format === 'csv' ? 'public.comma-separated-values-text' : 'public.json',
            dialogTitle: 'Save your Duebox export',
          });
        }
      }
      setDone(name);
    } catch (e) {
      setError(messageOf(e));
    } finally {
      setBusy(null);
    }
  };

  return (
    <Screen header={<Header />} testID="screen-export">
      <HeroBanner
        art="export"
        eyebrow="Your data, anytime"
        title="Export my data"
        lead="Everything in your household, as a file you keep — whether or not you subscribe."
        chips={[
          { icon: 'file', label: 'CSV for spreadsheets' },
          { icon: 'download', label: 'JSON, everything' },
          { icon: 'check', label: 'Always free' },
        ]}
      />

      <View style={{ gap: space.md }}>
        {WHAT.map((w) => (
          <View key={w.text} style={{ flexDirection: 'row', gap: space.md, alignItems: 'flex-start' }}>
            <Icon name={w.icon} size={20} color={c.brandInk} />
            <T style={{ flex: 1 }}>{w.text}</T>
          </View>
        ))}
      </View>

      {done ? <Banner icon="check" tone="good" message={`Exported ${done}.`} /> : null}
      {error ? <Banner icon="alert" message={error} /> : null}

      <View style={{ gap: space.sm }}>
        <Button label="Export as CSV (spreadsheet)" icon="download" onPress={() => void run('csv')} loading={busy === 'csv'} disabled={busy !== null} testID="export-csv" />
        <Button label="Export as JSON (everything)" tone="secondary" onPress={() => void run('json')} loading={busy === 'json'} disabled={busy !== null} testID="export-json" />
      </View>
      <T variant="caption" tone="faint">
        Scanned pages aren’t included in the file — open an item to save its pages.
      </T>
    </Screen>
  );
}
