import {
  AlarmClock,
  Gift,
  Heart,
  MessageCircle,
  AlertTriangle,
  ArrowRight,
  BadgeCheck,
  Bell,
  BellOff,
  Briefcase,
  Calendar,
  CalendarClock,
  Camera,
  Car,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  Crown,
  Download,
  FileText,
  GraduationCap,
  HeartPulse,
  Home,
  IdCard,
  Image as ImageIcon,
  Inbox,
  Info,
  Lock,
  LogOut,
  Mail,
  Minus,
  MoreHorizontal,
  Paperclip,
  Pencil,
  Plus,
  Receipt,
  Repeat,
  RotateCcw,
  ScanLine,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Trash2,
  User,
  UserPlus,
  Users,
  X,
  type LucideIcon,
} from 'lucide-react-native';
import { useColors } from '../theme/tokens';

/** A closed set: screens name an icon, never import lucide directly. */
const ICONS = {
  alarm: AlarmClock,
  alert: CircleAlert,
  warning: AlertTriangle,
  'arrow-right': ArrowRight,
  verified: BadgeCheck,
  bell: Bell,
  'bell-off': BellOff,
  case: Briefcase,
  calendar: Calendar,
  'calendar-clock': CalendarClock,
  camera: Camera,
  car: Car,
  check: Check,
  'check-all': CheckCheck,
  'check-circle': CircleCheck,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  copy: Copy,
  crown: Crown,
  download: Download,
  file: FileText,
  school: GraduationCap,
  health: HeartPulse,
  home: Home,
  passport: IdCard,
  image: ImageIcon,
  inbox: Inbox,
  info: Info,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  minus: Minus,
  more: MoreHorizontal,
  attach: Paperclip,
  pencil: Pencil,
  plus: Plus,
  receipt: Receipt,
  repeat: Repeat,
  undo: RotateCcw,
  scan: ScanLine,
  search: Search,
  settings: Settings,
  share: Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  star: Star,
  trash: Trash2,
  user: User,
  'user-plus': UserPlus,
  users: Users,
  gift: Gift,
  heart: Heart,
  message: MessageCircle,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 22, color, strokeWidth = 2 }: { name: IconName; size?: number; color?: string; strokeWidth?: number }) {
  const c = useColors();
  const Component = ICONS[name];
  return <Component size={size} color={color ?? c.text} strokeWidth={strokeWidth} />;
}
